import type { PostCard } from "@/types/post";

export const MOCK_CATEGORIES = [
  { id: "1", name: "Política", slug: "politica", color: "#dc2626" },
  { id: "2", name: "Saúde", slug: "saude", color: "#2563eb" },
  { id: "3", name: "Segurança", slug: "seguranca", color: "#7c3aed" },
  { id: "4", name: "Educação", slug: "educacao", color: "#ca8a04" },
  { id: "5", name: "Mobilidade Urbana", slug: "mobilidade-urbana", color: "#0d9488" },
  { id: "6", name: "Causa Animal", slug: "causa-animal", color: "#ea580c" },
];

export const MOCK_POSTS: PostCard[] = [
  {
    id: "1",
    title: "A agonia nas ruas e a omissão nos gabinetes: o colapso da causa animal em Piraquara",
    subtitle: "Sem abrigo, sem recolhimento e sob um surto silencioso de esporotricose",
    slug: "colapso-causa-animal-piraquara",
    excerpt:
      "A cidade terceiriza sua responsabilidade enquanto animais agonizam nas calçadas. Até quando dependeremos de favores políticos externos para fazer o básico?",
    coverImage: "https://images.unsplash.com/photo-1450778869188-41d0601e46e5?w=1200&q=80",
    publishedAt: new Date("2026-05-14"),
    featured: true,
    views: 2840,
    category: MOCK_CATEGORIES[5],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "2",
    title: "Urgente: Servidor da saúde é preso em flagrante após suspeita de abuso contra adolescente",
    slug: "servidor-saude-preso-piraquara",
    excerpt: "Caso chocou moradores e reacende debate sobre segurança e fiscalização na rede municipal.",
    coverImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80",
    publishedAt: new Date("2026-05-13"),
    featured: false,
    views: 5120,
    category: MOCK_CATEGORIES[1],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "3",
    title: "A importância da Guarda Municipal para a Sociedade",
    slug: "guarda-municipal-piraquara",
    excerpt: "Especialistas debatem o papel da GCM no enfrentamento à criminalidade e na proteção dos cidadãos.",
    coverImage: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80",
    publishedAt: new Date("2026-05-12"),
    featured: false,
    views: 1890,
    category: MOCK_CATEGORIES[2],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "4",
    title: "A pior nota do Paraná: Câmara de Piraquara recebe nota zero em fiscalização",
    slug: "camara-piraquara-nota-zero-tce",
    excerpt: "Avaliação do TCE-PR de 2025 expõe fragilidades no controle e transparência do Legislativo municipal.",
    coverImage: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1200&q=80",
    publishedAt: new Date("2026-05-11"),
    featured: false,
    views: 3420,
    category: MOCK_CATEGORIES[0],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "5",
    title: "Bonde Urbano Digital atrai olhares, mas revolta trabalhador por lentidão",
    slug: "bonde-urbano-digital-piraquara",
    excerpt: "Inovação de vitrine não convence quem depende do transporte público todos os dias na cidade.",
    coverImage: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&q=80",
    publishedAt: new Date("2026-05-10"),
    featured: false,
    views: 2100,
    category: MOCK_CATEGORIES[4],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "6",
    title: "Uniforme Escolar: O básico que virou luxo",
    slug: "uniforme-escolar-piraquara",
    excerpt: "Famílias relatam dificuldade para garantir material e vestuário no início do ano letivo.",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da280a02?w=1200&q=80",
    publishedAt: new Date("2026-05-09"),
    featured: false,
    views: 1650,
    category: MOCK_CATEGORIES[3],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "7",
    title: "Três mortos em 30 dias: A Jacomel que mata e o silêncio de quem deveria proteger",
    slug: "jacomel-seguranca-piraquara",
    excerpt: "Moradores cobram ações urgentes após sequência de homicídios na região.",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
    publishedAt: new Date("2026-05-08"),
    featured: false,
    views: 4200,
    category: MOCK_CATEGORIES[2],
    author: { name: "Redação Mobiliza" },
  },
  {
    id: "8",
    title: "A extinção dos piraquarenses e os R$ 100 milhões que não chegaram aqui",
    slug: "saude-piraquara-investimentos",
    excerpt: "Relatório aponta déficit crônico de investimentos na rede municipal de saúde.",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80",
    publishedAt: new Date("2026-05-07"),
    featured: false,
    views: 2980,
    category: MOCK_CATEGORIES[1],
    author: { name: "Redação Mobiliza" },
  },
];

export const MOCK_POST_CONTENT: Record<string, string> = {
  "colapso-causa-animal-piraquara": `<p>Piraquara vive um momento crítico na proteção animal. A ausência de abrigo municipal, a falta de políticas estruturadas de castração e o surto de esporotricose colocam em risco não apenas os animais, mas também a saúde pública.</p><p>Moradores e protetores independentes relatam que o recolhimento de animais em situação de maus-tratos depende de articulações informais e da boa vontade de poucos servidores — quando não da pressão nas redes sociais.</p><p>O Mobiliza Piraquara acompanha o tema e cobra posicionamento claro da gestão municipal sobre um plano de ação com prazos, orçamento e transparência.</p>`,
};
